spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  application:
         name: gaosheng-config-dev
---
spring:
  profiles: test #测试环境
  application:
         name: gaosheng-config-gaosheng-test
#保存为utf-8

